apiVersion: apps/v1
kind: Deployment
metadata:
  name: iap_deployment
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iap
  template:
    metadata:
      name: nginx-2
      labels:
        app: iap
    spec:
      containers:
      - name: nginx
        image: nginx