apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: iap-replicaset
  labels:
    app: iap 
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: iap
  template:
    metadata:
      name: nginx-1
      labels:
        app: iap
    spec:
      containers:
      - name: nginx
        image: nginx

