apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shared-ns
  name: shared-ns
spec:
  containers:
  - image: busybox
    name: p1
    command: ['/bin/sh','-c','sleep 10000']
  - image: nginx
    name: p2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
