apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
   - image: prvinsm21/ubuntu-nginx
     name: pod1
    #    env:
    #     - name: dbdata
    #       valueFrom:
    #        secretKeyRef:
    #         key: database
    #         name: secret4

    #    envFrom:
    #     - secretRef:
    #        name: secret4

     volumeMounts:
      - mountPath: /app/secrets
        name: mongosec
  volumes:
   - name: mongosec
     secret:
      secretName: dbsecret
