apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
   - image: prvinsm21/ubuntu-nginx
     name: pod1
    #    env:
    #     - name: dbdata
    #       valueFrom:
    #        secretKeyRef:
    #         key: database
    #         name: secret4

    #    envFrom:
    #     - secretRef:
    #        name: secret4

     volumeMounts:
      - mountPath: /app/secrets
        name: sec
  volumes:
   - name: sec
     secret:
      secretName: secret4
     items:
      - key: variable3
        path: /app/secrets/var3
      - key: variable4
        path: /app/secrets/var4
