apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu-sleeper-2
  name: ubuntu-sleeper-2
spec:
  containers:
  - image: prvinsm21/ubuntu-nginx
    name: ubuntu-sleeper-2
    command:
     - "sleep"
     - "5000"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
