apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy-green
  name: nginx-deploy-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-green
    spec:
      volumes:
      - name: webdata
        emptyDir: {}
      initContainers:
      - name: web-content
        image: busybox
        command: ['/bin/sh','-c','echo "<h1>I am <font color=green>GREEN</font></h1>" > /webdata/index.html']
        volumeMounts:
        - name: webdata
          mountPath: "/webdata"
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: webdata
          mountPath: "/usr/share/nginx/html"
