apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: analytics
  name: analytics
spec:
  containers:
  - image: registry.k8s.io/busybox
    name: analytics-iap
    command: ["/bin/sh", "-c", "env", "sleep", "3600"]
 #    args: [ "while true; do sleep 30; done;" ]
    env:
        - name: config
          valueFrom:
           configMapKeyRef:
            name: analytics-config
            key: store
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
