apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu-nginx
  name: ubuntu-nginx
spec:
  containers:
   - image: prvinsm21/ubuntu-nginx:v1
     name: ubuntu-nginx
     volumeMounts:
      - name: test
        mountPath: "/config"
        readOnly: true
  volumes:
   - name: test
     configMap:
      name: cm7
  restartPolicy: Always
