apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu-nginx
  name: ubuntu-nginx
spec:
  containers:
  - image: prvinsm21/ubuntu-nginx:v1
    name: ubuntu-nginx
    envFrom:
     - configMapRef:
        name: cm7
    #    env:
    #     - name: envfromcm 
    #       valueFrom:
    #        configMapKeyRef:
    #         name: cm2
    #         key: log4j.properties
  restartPolicy: Always
