apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod5
spec:
  containers:
  - image: prvinsm21/ubuntu-nginx
    name: pod
    #  nodeSelector:
    #   IAP: "Console"
