apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-engine
  name: nginx-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-engine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-engine
    spec:
      containers:
      - image: nginx
        name: nginx



---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-engine
spec:
  type: NodePort
  selector:
    app: nginx-engine
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30011
