apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop
  labels:
    app: coffee
spec:
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: prvinsm21/coffeeshop:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
spec:
  selector:
    app: coffee
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-coffee
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coffee-svc
            port:
              number: 3000
