apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop
  labels:
    app: coffee
spec:
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: prvinsm21/coffeeshop:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
spec:
  selector:
    app: coffee
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
    - port: 443
      nodePort: 30443
      name: https
