apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: webapp4
  name: 4-prog
spec:
  containers:
  - image: prvinsm21/coffeeshop:v1
    name: 4-prog
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
