apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: randomnumber
  name: randomnumber
spec:
  containers:
  - image: alpine
    name: randomnumber
    command: ["/bin/sh","-c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
