apiVersion: v1
kind: Pod
metadata:
  name: prog3
spec:
  volumes:
    - name: pv-prog3
      persistentVolumeClaim:
        claimName: pvc-prog3
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh","-c"]
      args: ["shuf -i 0-100 -n 1 >> /opt/data3/numbers.txt;"]
      volumeMounts:
        - mountPath: "/opt/data3"
          name: pv-prog3
