apiVersion: v1
kind: Pod
metadata:
  name: prog1
spec:
  containers:
   - name: alpine
     image: alpine
     command: ["/bin/sh","-c"]
     args: ["shuf -i 0-100 -n 1 >> /opt/data/number.out;"]
     volumeMounts:
      - name: data-volume1
        mountPath: /opt/data
  volumes:
   - name: data-volume1
     persistentVolumeClaim:
      claimName: pvc-prog1
