apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prog3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data3"
