apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prog6
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
