apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      
      # Nginx Container
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          #command: ["/bin/sh"]
          #args: ["-c", "while true; do echo hello; sleep 10;done"]
        command: ['sh','-c']
        args:
        - while true;
           do
           echo "$(date) INFO Some app data" >> /var/log/myapp.log;
           sleep 5;
          done
        volumeMounts:
        - name: log-data-prog7
          mountPath: /var/log

      # SideCar Container
      - name: log-sidecar
        image: busybox:1.28
        volumeMounts:
        - name: log-data-prog7
          mountPath: /var/sidecar
        command: ['sh','-c']
        args: ["tail -f /var/sidecar/myapp.log"]

        # volumeMounts:
        #- name: log-data-prog7
        #  mountPath: /var/sidecar

      volumes:
      - name: log-data-prog7
        emptyDir: {}


