apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: 2-prog
  name: 2-prog
spec:
  containers:
  - image: busybox
    name: 2-prog
    command : ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    - name: username
      valueFrom:
       secretKeyRef:
        name: 2-secret
        key: username
