apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: 3-pod
  name: 3-pod
spec:
  volumes:
  - name: vol3
    secret:
     secretName: 3-secret
  containers:
  - image: busybox
    name: 3-pod
    command: ["/bin/sh"]
    args: ["-c", "sleep 500"]
    volumeMounts:
    - name: vol3
      mountPath: /vol3
