apiVersion: v1
kind: Pod
metadata:
  labels:
    run: compute
  name: compute
spec:
  containers:
  - image: busybox
    name: compute
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    - name: comfig
      valueFrom:
       secretKeyRef:
        name: compute-secret
        key: USER_NAME
