apiVersion: v1
data:
  password: YWRtaW4xMjM=
  username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2022-11-04T15:11:47Z"
  name: mysecret-2
  namespace: default
  resourceVersion: "1516051"
  uid: 3386a4b4-c0cf-4187-a849-b5f1ff373d09
type: Opaque
