apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test1
  name: test1
spec:
  containers:
  - image: busybox
    name: test1
    command: ["/bin/sh"]
    args: ["-c","sleep 600"]
    env:
    - name: myusername
      valueFrom:
       secretKeyRef:
        name: mysecret-2
        key: username
